Repository Mobile-and-Ubiquitous-Computing-2020-1/team4, pull requests merged in 2020-05, with the labels that each got.

#28 Poi to geofence
  cicerone/.idea/misc.xml
  cicerone/app/build.gradle
  cicerone/app/src/main/AndroidManifest.xml
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofencingController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/NotificationsController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/POI.kt
  cicerone/app/src/main/res/layout/activity_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_geofence_triggered.xml
  cicerone/app/src/main/res/values/strings.xml
Labels: ready-for-review, ui/ux, user context

#30 Retrieving POI data from Foursquare API using location information
  cicerone/.gitignore
  cicerone/app/build.gradle
  cicerone/app/src/main/AndroidManifest.xml
  cicerone/app/src/main/java/com/teampower/cicerone/DataController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/LocationController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/Place.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/Categories.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/FoursquareAPI.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/FoursquareData.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/FoursquareRequestInterceptor.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/FoursquareResponse.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/Icon.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/LabeledLatLngs.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/Location.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/Meta.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/Response.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/VenuePage.kt
  cicerone/app/src/main/java/com/teampower/cicerone/foursquare/Venues.kt
  cicerone/app/src/main/res/layout/content_scrolling.xml
Labels: data retrieval, ready-for-review

#33 Poi intent
  cicerone/app/build.gradle
  cicerone/app/src/main/java/com/teampower/cicerone/DataController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofencingController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/LocationController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/NotificationsController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/POI.kt
  cicerone/app/src/main/java/com/teampower/cicerone/Place.kt
  cicerone/app/src/main/java/com/teampower/cicerone/WikiInfoManager.kt
  cicerone/app/src/main/res/layout/activity_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_scrolling.xml
  cicerone/app/src/main/res/values/dimens.xml
  cicerone/app/src/main/res/values/strings.xml
Labels: content generation, data retrieval, ui/ux, user context

#42 Tts
  cicerone/app/build.gradle
  cicerone/app/src/main/java/com/teampower/cicerone/DataController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofencingController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/WikipediaResponseModels.kt
  cicerone/app/src/main/res/layout/activity_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_geofence_triggered.xml
  cicerone/app/src/main/res/values/strings.xml
Labels: content generation, ready-for-review

#41 First MVP of working database
  cicerone/app/build.gradle
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/POI.kt
  cicerone/app/src/main/java/com/teampower/cicerone/adapters/POIHistoryListAdapter.kt
  cicerone/app/src/main/java/com/teampower/cicerone/adapters/POISavedListAdapter.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/DataController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/GeofencingController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/LocationController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/NotificationsController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/CategoryDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/CiceroneAppDatabase.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/Entities.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/POIHistoryDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/POISavedDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/repositories/CategoryRepository.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/repositories/POIHistoryRepository.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/repositories/POISavedRepository.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/CategoryViewModel.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/POIHistoryViewModel.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/POISavedViewModel.kt
  cicerone/app/src/main/java/com/teampower/cicerone/wikipedia/RestAPI.kt
  cicerone/app/src/main/java/com/teampower/cicerone/wikipedia/WikiInfoManager.kt
  cicerone/app/src/main/java/com/teampower/cicerone/wikipedia/WikipediaResponseModels.kt
  cicerone/app/src/main/java/com/teampower/cicerone/wikipedia/WikipediaService.kt
  cicerone/app/src/main/res/layout/content_scrolling.xml
  cicerone/app/src/main/res/layout/recyclerview_item.xml
  cicerone/app/src/main/res/values/colors.xml
  cicerone/app/src/main/res/values/dimens.xml
  cicerone/app/src/main/res/values/strings.xml
  cicerone/app/src/main/res/values/styles.xml
  cicerone/build.gradle
Labels: general, ready-for-review

#46 User feedback
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/POI.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/DataController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/CategoryDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/CiceroneAppDatabase.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/Entities.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/repositories/CategoryRepository.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/CategoryViewModel.kt
  cicerone/app/src/main/res/layout/activity_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_geofence_triggered.xml
  cicerone/app/src/main/res/values/strings.xml
Labels: ready-for-review, ui/ux

#48 Clean ui
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/ListSavedPOIActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/POI.kt
  cicerone/app/src/main/java/com/teampower/cicerone/adapters/POIHistoryListAdapter.kt
  cicerone/app/src/main/java/com/teampower/cicerone/adapters/POIListAdapter.kt
  cicerone/app/src/main/java/com/teampower/cicerone/adapters/POISavedListAdapter.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/DataController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/LocationController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/control/NotificationsController.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/CiceroneAppDatabase.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/Entities.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/POIDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/POIHistoryDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/POISavedDao.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/repositories/POIRepository.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/repositories/POISavedRepository.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/POIHistoryViewModel.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/POISavedViewModel.kt
  cicerone/app/src/main/java/com/teampower/cicerone/viewmodels/POIViewModel.kt
  cicerone/app/src/main/res/layout/activity_scrolling.xml
  cicerone/app/src/main/res/layout/content_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_list_pois.xml
  cicerone/app/src/main/res/layout/content_scrolling.xml
  cicerone/app/src/main/res/layout/item_poi.xml
  cicerone/app/src/main/res/layout/recyclerview_item.xml
  cicerone/app/src/main/res/values/colors.xml
  cicerone/app/src/main/res/values/dimens.xml
  cicerone/app/src/main/res/values/strings.xml
  cicerone/app/src/main/res/values/styles.xml
Labels: ui/ux

#49 Implement proper layout on detail activity
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceBroadcastReceiver.kt
  cicerone/app/src/main/java/com/teampower/cicerone/GeofenceTriggeredActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/MainActivity.kt
  cicerone/app/src/main/java/com/teampower/cicerone/database/POIDao.kt
  cicerone/app/src/main/res/drawable/ic_thumb_down.xml
  cicerone/app/src/main/res/drawable/ic_thumb_up.xml
  cicerone/app/src/main/res/layout/activity_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_geofence_triggered.xml
  cicerone/app/src/main/res/layout/content_list_pois.xml
  cicerone/app/src/main/res/layout/content_scrolling.xml
  cicerone/app/src/main/res/layout/item_poi.xml
  cicerone/app/src/main/res/values/colors.xml
  cicerone/app/src/main/res/values/dimens.xml
  cicerone/app/src/main/res/values/strings.xml
  cicerone/app/src/main/res/values/styles.xml
Labels: ui/ux
